# Generated by Django 3.0.5 on 2020-04-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discountprice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
