# Generated by Django 3.0.5 on 2020-04-26 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_discountprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='discountprice',
            new_name='discount_price',
        ),
    ]
