# Generated by Django 3.0.5 on 2020-04-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantitiy',
            field=models.IntegerField(default=1),
        ),
    ]
