# Generated by Django 3.0.5 on 2020-04-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200426_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='additional_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Sell'), ('B', 'Buy'), ('H', 'Hardware')], max_length=2),
        ),
    ]
